[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - LOGS_CAPTURED - Started capturing logs in process (pid: 627895).
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - STEP_START - Started execution of step "linear_regression".
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - linear_regression - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/test_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - LOADED_INPUT - Loaded input "test_data" using input manager "io_manager", from output "test_data" of step "train_test_data"
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - linear_regression - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/train_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - LOADED_INPUT - Loaded input "train_data" using input manager "io_manager", from output "train_data" of step "train_test_data"
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - STEP_INPUT - Got input "test_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - STEP_INPUT - Got input "train_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:09:43 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - e8311c73-61c0-41cc-9f90-7ebf21076b8f - 627895 - linear_regression - STEP_FAILURE - Execution of step "linear_regression" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "linear_regression"::

UnboundLocalError: cannot access local variable 'test_input' where it is not associated with a value

Stack Trace:
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 490, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/kai/Git/twai_mlops_assignment2-main/src/bike_share/assets/models.py", line 56, in linear_regression
    test_input = test_input.dropna()
                 ^^^^^^^^^^
[0m
