[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - LOGS_CAPTURED - Started capturing logs in process (pid: 639593).
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - STEP_START - Started execution of step "xgboost_regressor".
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - xgboost_regressor - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/test_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - LOADED_INPUT - Loaded input "test_data" using input manager "io_manager"
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - xgboost_regressor - Loading file from: /home/kai/Git/twai_mlops_assignment2-main/src/tmp9wf98lfe/storage/train_data using PickledObjectFilesystemIOManager...
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - LOADED_INPUT - Loaded input "train_data" using input manager "io_manager"
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - STEP_INPUT - Got input "test_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - STEP_INPUT - Got input "train_data" of type "DataFrame". (Type check passed).
[32m2024-12-11 15:29:00 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 5be1c140-f467-48b3-b0ad-51d98d0fc28d - 639593 - xgboost_regressor - STEP_FAILURE - Execution of step "xgboost_regressor" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "xgboost_regressor"::

NameError: name 'pipeline' is not defined. Did you mean: 'Pipeline'?

Stack Trace:
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 490, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/kai/miniconda3/envs/bike-share/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/kai/Git/twai_mlops_assignment2-main/src/bike_share/assets/models.py", line 79, in xgboost_regressor
    grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring="neg_mean_absolute_error", verbose=2, n_jobs=-1)
                               ^^^^^^^^
[0m
